language: cpp
dist: trusty
sudo: required
compiler: clang

env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
addons:
  apt:
    packages:
      - clang-3.8
    sources: *sources

install: 
  # clang
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 90
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 90
  - sudo update-alternatives --install /usr/bin/ld ld /usr/bin/llvm-ld 90
  # clang STL
  - sudo apt-get install -y libc++-dev libc++abi-dev

script:
  - clang++-3.8 -v
  - clang++-3.8 -o main -std=c++14 -stdlib=libc++ main.cpp
  - clang++ -v
  - clang++ -o main -std=c++14 -stdlib=libc++ main.cpp
