language: generic
os: linux
env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
addons:
  apt:
    packages:
      - clang-3.8
    sources: *sources

script:
  - clang++-3.8 -v
  - clang++-3.8 -o main -std=c++14 main.cpp
  - clang++ -v
  - clang++ -o main -std=c++14 main.cpp